export const DB = {
  FETCH: 'DATABASE_FETCH',  
  SUCCESS: 'DATABASE_SUCCESS',
  FAILED: 'DATABASE_FAILED',
  CLOSE: 'DATABASE_CLOSE',
}

export const QUERY = {
  FETCH: 'QUERY_FETCH',  
  SUCCESS: 'QUERY_SUCCESS',
  FAILED: 'QUERY_FAILED',
}