export const STORE = {
  SET_STORE: "SET_STORE"
}

export const APP = {
  SET_LOADING: 'SET_LOADING'
}

export const MASTER = {
  SET_CATEGORY_ITEM_FETCH: 'SET_CATEGORY_ITEM_FETCH',
  SET_CATEGORY_ITEM_SUCCESS: 'SET_CATEGORY_ITEM_SUCCESS',
  SET_CATEGORY_ITEM_FAILED: 'SET_CATEGORY_ITEM_FAILED'
}